export const PRODUCT_LOADED_SUCCESS = "PRODUCT_LOADED_SUCCESS";
export const PRODUCT_LOADED_FAIL = "PRODUCT_LOADED_FAIL";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";